server:
  port: 8082

# mysql config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finetech
    username: finetech_user
    password: finetech_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
